
@BaseUrl http://localhost:7123/api

POST {{BaseUrl}}/PromotionalHTTPFunction
Content-Type: application/json

{
  "TemplateId": 4,
  "PromotionType": "Email"
}

###

GET {{BaseUrl}}/GetAccountInformtaionFunction
Content-Type: application/json

###

GET {{BaseUrl}}/Unsubscribe?token=sanujaariyapperuma%40gmail.com|Gm5VzQWUItm1YndyDCpx2WiVY561slyEE8My_60zzxQ